# ROOT_PATH is defnied by including make file

CONCURRENCY_LIB_PATH := $(ROOT_PATH)/Concurrency-Lib

include $(CONCURRENCY_LIB_PATH)/Common.mk

# OVERRIDE
CXX := g++
CXXFLAGS := -Wall -Wextra -g -O0 -std=c++17 -MMD -MP

PACKET_SIMULATIONS_SRC := $(ROOT_PATH)/PacketSimulationEngine/src

PACKET_GENERATION_PATH = $(PACKET_SIMULATIONS_SRC)/PacketGeneration
STATISTICS_COUNTER_PATH = $(PACKET_SIMULATIONS_SRC)/Statistics
PACKET_SINK_PATH := $(PACKET_SIMULATIONS_SRC)/PacketSink


INCLUDES := $(CONCURRENCY_LIB_INCLUDES) \
-I$(PACKET_GENERATION_PATH) \
-I$(STATISTICS_COUNTER_PATH) \
-I$(PACKET_SINK_PATH)